'use strict';

const FB_PAGE_TOKEN = "EAAJzUjQMm7cBAFoEh2Tbu8Xdf4eay9NWGfm7ycFuixdsNXHQfyWcakQt9rz9xyTv6aKDi66AoShuAzvgZBXlIkY8NvXPXL7CTQhVqxJmyV16ZC4G3l5ZCK0Nu9FTY1r9DaUzdOStoWJuVasJ908hTeRdbTm5M99N2ZCZASqdchwZDZD"
const WIT_TOKEN = "ELKAFRRNUCA2II6FZAC65L3Q5NMYN6RJ"
const FB_APP_SECRET = "82334ed66b5e2d0e65b6de9a6ca4ff6a"
const FB_VERIFY_TOKEN = "my_voice_is_my_password_verify_me"

module.exports = {
  FB_PAGE_TOKEN: FB_PAGE_TOKEN,
  WIT_TOKEN: WIT_TOKEN,
//  FB_APP_SECRET: FB_APP_SECRET,
  FB_VERIFY_TOKEN: FB_VERIFY_TOKEN
}
